dist: trusty
language: node_js
node_js:
  - lts/*

branches:
  only:
    - gh-pages

env:
  global:
    - URL="http://w3c.github.io/manifest/ECHIDNA"
    - DECISION="https://lists.w3.org/Archives/Public/public-webapps/2014JulSep/0627.html"
    - secure: "vuLLjmy5cSalvR4ut2Q28YJgVUoSmLQYlhNRyF7zVskO5VFX7RHpfWokrk1SXEQ5hI8bpWOYJOVrcYr05BP0cFvsESlDejaur4rw/gT2nfMkuyWbVhbxH9mFYKeVFWpoC+iezrao9VjMRYySjEJAM4B9mXflN3MQ6ddRaQlBMaI="

install:
  - npm install respec-validator

script:
  - npx respec-validator --no-links --gh-token=$GH_TOKEN index.html

cache:
  directories:
    - node_modules

after_success:
  - CC="mcaceres@mozilla.com,mgiuca@google.com"
  - echo "If it fails, check https://lists.w3.org/Archives/Public/public-tr-notifications/"
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && curl "https://labs.w3.org/echidna/api/request" --data "cc=$CC" --data "url=$URL" --data "decision=$DECISION" --data "token=$TOKEN"'
